# This image is based on the ros2 images and contains RVIZ2 for debugging.
FROM duna-nomad-base

# Clone rviz2 humble, build and clean up.
RUN printf 'repositories:\n ros2/rviz:\n  type: git\n  url: https://github.com/ros2/rviz.git\n  version: humble' > ${ROS_EXTRA_ROOT}/rviz2.repo && \
  cd ${ROS_EXTRA_ROOT} && mkdir src && vcs import src < rviz2.repo && \
  apt update && source ${ROS_BASE_INSTALL} && rosdep install -y --from-paths src --ignore-src && \
  source ${ROS_BASE_INSTALL} && colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release && \
  echo "source ${ROS_EXTRA_ROOT}/install/setup.bash" >> /root/.bashrc && \
  rm -rf ${ROS_EXTRA_ROOT}/src && \
  rm -rf /var/lib/apt/lists/* && \
  apt-get autoremove -y && apt-get clean

ENV DISPLAY=:0